# Generated by Django 4.0.4 on 2022-05-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kategori', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Firmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(max_length=255)),
                ('zdjecia', models.ImageField(upload_to='')),
                ('strona_www', models.URLField()),
                ('telefon', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('kategoria', models.ManyToManyField(to='firmy.kategorie', verbose_name='kategorie')),
            ],
        ),
    ]
