# Generated by Django 4.0.4 on 2022-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0002_kategorie_zdj'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmy',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firmy',
            name='kategoria',
            field=models.ManyToManyField(to='firmy.kategorie', verbose_name='kategoria'),
        ),
    ]
