# Generated by Django 4.0.4 on 2022-05-23 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0003_firmy_opis_alter_firmy_kategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmy',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
