# Generated by Django 4.0.4 on 2022-05-23 08:43

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0004_firmy_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmy',
            name='lokalizacja',
            field=location_field.models.plain.PlainLocationField(default=-1, max_length=63),
            preserve_default=False,
        ),
    ]
