# Generated by Django 4.0.4 on 2022-05-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0005_firmy_lokalizacja'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmy',
            name='miasto',
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
