# Generated by Django 4.0.4 on 2022-06-07 10:57

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0007_alter_firmy_email_alter_firmy_miasto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmy',
            name='kategoria',
            field=models.ManyToManyField(default=1, to='firmy.kategorie', verbose_name='kategoria'),
        ),
        migrations.AlterField(
            model_name='firmy',
            name='lokalizacja',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
