# Generated by Django 4.0.4 on 2022-06-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0008_alter_firmy_kategoria_alter_firmy_lokalizacja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmy',
            name='kategoria',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='firmy.kategorie', verbose_name='kategoria'),
        ),
    ]
