# Generated by Django 4.0.5 on 2022-06-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0010_alter_firmy_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmy',
            name='zdjecia',
            field=models.ImageField(default='default.png', null=True, upload_to='upload_avatar/'),
        ),
    ]
