# Generated by Django 4.0.5 on 2022-06-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0011_alter_firmy_zdjecia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmy',
            name='zdjecia',
            field=models.ImageField(default='default.png', upload_to='upload_avatar/'),
        ),
    ]
