# Generated by Django 4.0.5 on 2022-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0012_alter_firmy_zdjecia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='firmy',
            name='kategoria',
        ),
        migrations.DeleteModel(
            name='Kategorie',
        ),
        migrations.AddField(
            model_name='firmy',
            name='category',
            field=models.ManyToManyField(blank=True, default=1, to='firmy.categories', verbose_name='category'),
        ),
    ]
