# Generated by Django 4.0.5 on 2022-06-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0013_categories_remove_firmy_kategoria_delete_kategorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmy',
            old_name='nazwa_firmy',
            new_name='business_name',
        ),
    ]
