# Generated by Django 4.0.5 on 2022-06-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0014_rename_nazwa_firmy_firmy_business_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmy',
            old_name='lokalizacja',
            new_name='localization',
        ),
    ]
