# Generated by Django 4.0.5 on 2022-06-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firmy', '0015_rename_lokalizacja_firmy_localization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmy',
            old_name='zdjecia',
            new_name='image',
        ),
    ]
